### ISSUE TITLE
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.

### ISSUE THREAD

**Issue by rdugue** [grpc/grpc-kotlin#437]
I am getting the following error when using the protobuf Plugin and the protoc compiler:
`protoc: stdout: . stderr: /builds/rdugue1/Arcade-Phito-Backend/.gradle/caches/modules-2/files-2.1/io.grpc/protoc-gen-grpc-java/1.57.2/d3f50bdc45086ae0d90f95e362fb506221940c2e/protoc-gen-grpc-java-1.57.2-linux-x86_64.exe: program not found or is not executable
  Please specify a program using absolute path or make sure the program is available in your PATH system variable
  --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.`

Here are the versions I am working with:
```
grpc_version=1.57.2
grpc_kotlin_version=1.4.0
protobuf_version=3.24.1
```

Here is my gradle configuration:
```gradle
plugins {
    kotlin("jvm") version "1.9.0"
    kotlin("plugin.serialization") version "1.9.0"
    id("com.google.protobuf") version "0.9.4"
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
    implementation("io.grpc:grpc-kotlin-stub:$grpc_kotlin_version")
    implementation("io.grpc:grpc-protobuf:$grpc_version")
    implementation("io.grpc:grpc-netty:$grpc_version")
    implementation("com.google.protobuf:protobuf-java:$protobuf_version")
    implementation("com.google.protobuf:protobuf-kotlin:$protobuf_version")
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$protobuf_version"
    }
    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:$grpc_version"
            //path = "/usr/local/bin/protoc-gen-grpc-java.exe"
        }
        id("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:${grpc_kotlin_version}:jdk8@jar"
        }
    }
    generateProtoTasks {
        all().forEach {
            it.plugins {
                id("grpc")
                id("grpckt")
            }
            it.builtins {
                id("kotlin")
            }
        }
    }
}
```

When I run the project locally in Intellij using the Maven artifact (you can see the path version is commented out above), it works just fine. But it fails with the above error when using my continuous integration setup. I was getting the above error using the artifact variable, so I switched to the path to test using this `gitlab-ci.yml` setup:

```yaml
image: gradle:8.1.1-jdk17-alpine

variables:
  GRPC_JAVA_PROTOC_GEN_URL: https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.57.2/protoc-gen-grpc-java-1.57.2-linux-x86_64.exe

before_script:
  - export PATH="/usr/local/bin:$PATH"
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew
  - wget $GRPC_JAVA_PROTOC_GEN_URL -O /usr/local/bin/protoc-gen-grpc-java.exe
  - chmod +x /usr/local/bin/protoc-gen-grpc-java.exe
  - ls -l /usr/local/bin

...
```
I did this to confirm that the file is indeed in the right directory and is executable. But I still received the same error:
`protoc: stdout: . stderr: /usr/local/bin/protoc-gen-grpc-java.exe: program not found or is not executable
  Please specify a program using absolute path or make sure the program is available in your PATH system variable
  --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.`
 I would appreciate any help figuring out what's happening and please let me know if I can provide any more details to make this more clear.
